apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ghostkube-mutating-webhook
webhooks:
  - name: mutate-pods.ghostkube.io
    clientConfig:
      service:
        name: ghostkube-webhook
        namespace: default
        path: /mutate 
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlERHpDQ0FmZWdBd0lCQWdJVVFLYlhWdHFEalhEOXFWRmxMeVRCZjYyYjQ2NHdEUVlKS29aSWh2Y05BUUVMDQpCUUF3RnpFVk1CTUdBMVVFQXd3TVoyaHZjM1JyZFdKbExXTmhNQjRYRFRJMk1ERXdPREl6TlRJek1Wb1hEVE0yDQpNREV3TmpJek5USXpNVm93RnpFVk1CTUdBMVVFQXd3TVoyaHZjM1JyZFdKbExXTmhNSUlCSWpBTkJna3Foa2lHDQo5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcDg4VnI4VzRDK09jajF6TjdJOFgra0E4MEJ3UzhJeHlVK25zDQpmYkRuajdjY2tnak9Td0NvUm1CZnoxTGlKOEZSL3JiZm5WNHBjaE52czhkMUhhTWpPa0QyMkxIREhLMzFPYlBzDQpIVUhVZ1JpdUJFaHRhRXA5ZGFHSm5VWEU3aUJFVDE1eUNqb1ZSZElwNW9XenRMa1V0OTFUR3hCS0YzUUs5ZjQvDQpUWlVtODc0Q0RocGlHOW5HaS9WeDJZOUpiQ1ZpSTdJR1NFLzZmQkl4VWUyL3ZNVThiYi9MOUs3ZjEwZFVrY3dTDQpydlBuTkkwRW5sa2gxWC9Ddk05dG1DcUV4TUZiYUV6NitoRVNNOFpWSzh3b2ZpR2x5aXJjKzIramdOOFZkVk4rDQo3NXdsR0ZkVC9EQlg5OEpBVER3UVhFQ0lrSjJBNm15VEs2cThWMzRzQktNeFJ2b09lUUlEQVFBQm8xTXdVVEFkDQpCZ05WSFE0RUZnUVVTejgzeXpZS3M0dzZ1TUN1RmRVZk9SU0NlVVV3SHdZRFZSMGpCQmd3Rm9BVVN6ODN5ellLDQpzNHc2dU1DdUZkVWZPUlNDZVVVd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DDQpBUUVBUG9laWZFdW1SWHF0U3lEL2xpQ2NENnE4NVJBK2xOaDJSYUhCY0FLYXBBd0tyZUNXZHpzclBHK1FvYlZiDQoyL3B4U1l5N0RzcFlmZmVyb1MrYVgrZDNCWEVYNHhyd2FTS3gydjRNS3hQaVdVVXhOZU05WlZGdVRhZ3Z4SDllDQp5YWl1ZXloUk9IeExJVzBzL1pkdEt1M3BtTVRJVDY2MERKQit3SUM5MFU5VFdyV255R0ZGWGw1ZzBqbzFSRSsrDQpBb2k3V2tiZUZ3WHY5cGQxUXo1NkhuYTRMdEJVSGRNUG9jcnFOSEpNQkEyVEZoZWhaTjJxRkF0QWlIeituV05HDQo5ZVNYSlMvcHVXYVVhM014Y3pjWGN2T2VGSWJ4cFozQ3EwTlNEamFlVGpKVkRwelhtUWtFcytXbytLMXNqdnBrDQpUVWhKNTYveUR5YVlEYmYrVW9HUm14YjRHUT09DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tDQo=
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    timeoutSeconds: 10
