apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-auth
  template:
    metadata:
      labels:
        app: hello-auth
        ghostkube.io/service: "auth-service"
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          command: ["/bin/sh", "-c", "sleep 3600"]